export const ADD_TOCART_LOADING="ADD_TOCART_LOADING";
export const ADD_TOCART_SUCCESS="ADD_TOCART_SUCCESS";
export const ADD_TOCART_ERROR="ADD_TOCART_ERROR";

export const GET_PRODUCTS_LOADING="GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR="GET_PRODUCTS_ERROR";

export const PATCH_TODO_LOADING="PATCH_TODO_LOADING";
export const PATCH_TODO_SUCCESS="PATCH_TODO_SUCCESS";
export const PATCH_TODO_ERROR="PATCH_TODO_ERROR";

export const DELETE_TODO_LOADING="DELETE_TODO_LOADING";
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS";
export const DELETE_TODO_ERROR="DELETE_TODO_ERROR";

export const SIGNUP_TODO_LOADING="SIGNUP_TODO_LOADING";
export const SIGNUP_TODO_SUCCESS="SIGNUP_TODO_SUCCESS";
export const SIGNUP_TODO_ERROR="SIGNUP_TODO_ERROR";

export const LOGIN_TODO_LOADING="LOGIN_TODO_LOADING";
export const LOGIN_TODO_SUCCESS="LOGIN_TODO_SUCCESS";
export const LOGIN_TODO_ERROR="LOGIN_TODO_ERROR";
export const LOGOUT="LOGOUT";